# Generated by Django 4.2.16 on 2024-11-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Perchase",
            new_name="Purchase",
        ),
    ]
