# Generated by Django 4.2.16 on 2024-11-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_perchase_purchase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="purchase_data",
            new_name="purchase_date",
        ),
    ]
