# Generated by Django 4.2.16 on 2024-12-21 07:27
# 環境毎に読み込ませる情報を変える方法

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def insert_category(apps, schema_editor):
    # 環境毎に依存する名称の設定ファイルを作成しているため、そこから環境を特定する
    setting_file = settings.SETTINGS_MODULE # manage.py実行時に渡される--settingsの値を取得
    env_name = setting_file.split('.')[-1] # ピリオドで区切った最後 (config.settings.development)

    if env_name == 'development':
        # 開発環境での処理
        Category = apps.get_model('inventory', 'Category')
        Category.objects.create(name='Category for development', parent_category=None)
    else:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_dml_insert_category_data_by_model"),
    ]

    operations = [
        migrations.RunPython(insert_category),
    ]